default: &default
  adapter: mysql2
  pool: 10
  timeout: 5000
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *default
  database: findout_development

test:
  <<: *default
  database: findout_test

production:
  <<: *default
  database: findout_production
